### ISSUE TITLE
`cb() never called!` or `Error: Cannot find module 'percy-client'`

### ISSUE THREAD

**Issue by briangonzalez** [percy/ember-percy#34]
```js
// index.js
const ep = require('ember-percy')
```
results in:

```sh
▵  node index.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'percy-client'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bgonzalez/code/_scratch/ember-percy-demo/node_modules/ember-percy/index.js:9:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by briangonzalez** [comment]
It looks as if `npm run prepubllsh` is not working for this repo:

```sh
▵  ls node_modules/percy-client/dist

#=> Nothing 
```

**Comment by LevelbossMike** [comment]
This breaks for me on node 6.10.0. As well. When installing via yarn I get:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/percy-client/-/percy-client-2.1.1.tgz: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
```

npm just errors with

```
npm ERR! cb() never called!
```

this seem to be related to the latest percy-client update and breaks our CI :/

**Comment by LevelbossMike** [comment]
Temporary fix: `npm install --save-dev percy-client@2.1.0` fixes the install issue.

**Comment by djones** [comment]
Hi, just letting you know we're looking into this at the moment and hope to have a fix within a few hours.

**Comment by fotinakis** [comment]
Hey all, this is now fixed, we had a corrupt npm package. The underlying dependency is now percy-client 2.1.3 which includes the fix. Thanks for reporting this!
